[profile.default]
out = 'out'
libs = ['lib']
ffi = true
fuzz_runs = 1000
fs_permissions = [
    { access = "read", path = "./test/data-structures/mocks/InstantiatedArrays.huff" },
    { access = "read", path = "./test/data-structures/mocks/InstantiatedHashmap.huff" },
    { access = "read", path = "./test/math/mocks/FixedPointMathWrappers.huff" },
    { access = "read", path = "./test/math/mocks/SafeMathWrappers.huff" },
    { access = "read", path = "./test/math/mocks/MathWrappers.huff" },
    { access = "read", path = "./test/math/mocks/TrigonometryWrappers.huff" },
    { access = "read", path = "./test/tokens/mocks/ERC1155Wrappers.huff" },
    { access = "read", path = "./test/utils/mocks/BitPackLibWrappers.huff" },
    { access = "read", path = "./test/utils/mocks/ErrorsMock.huff" },
    { access = "read", path = "./test/utils/mocks/JumpTableUtilWrappers.huff" },
    { access = "read", path = "./test/utils/mocks/MerkleProofLibWrappers.huff" },
    { access = "read", path = "./test/utils/mocks/MulticallableWrappers.huff" },
    { access = "read", path = "./test/utils/mocks/LibBitWrapper.huff" },
]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "foundry-huff/=lib/foundry-huff/src/",
    "solmate/=lib/solmate/src/"
]
